### ISSUE TITLE
Support for dynamic props

### ISSUE THREAD

**Issue by metagrover** [appbaseio/reactivebase-native#13]
This includes:

- `sortBy`
- `size`
- `from` *
- `dataField`
- `react`
- `defaultSelected`
- `pagination` *
- `highlight` *
- `highlightField` *
- `customQuery`
- `data` *
- `range` *
- `rangeLabels` *
- `queryFormat` *
- `autoSuggest` *

`*` denotes wherever necessary

**Comment by divyanshu013** [comment]
Need to add `rangeLabels` feature

Also would need to add support for some more formats in Date components IMO. Eg `date_time_no_millis`. I was able to test that it works with XDate in a gitxplore example.
ref - [gitxplore dataset](https://opensource.appbase.io/dejavu/live/#?input_state=XQAAAALLAQAAAAAAAAA9iIqnY-B2BnTZGEQz6wkFsXzANcEiOj1t75YJPmGw7xeXjnOyOKwcTIJQljSmiDlmnS0idduXRCWx36R0WY9_Vp2OeiWvs5xdlMjiRDDupmmjgc5kXonz8uq6m2RqZAJEc_g63epaXm2VZJ6P017RqXwhNW50YP02uGPJzw_wlnNHejyw3A55t3utzVz2q2hEOY3H9pHAg7K_wfl8eXKIKWBPWuje-SpDN0gQJYjHXF81VKoRy4eSVFxTmVq2rWCqSNB7pcVF9tc76xfZ4vOZCZURcF5b3yYKTn5mRjrAUayVMeVF_H_mD47E1-FSqJf48XJqASZOqbMHf1G8_6JwplFFNYetxKX96aldFD0boBdt5bGZcDlf_0vKBAwoDnz5OQDI_aQx0zNVwtNZxRplGpP7iaQNeBP7WhH-)
Would need to update reactivecore

Except Date components, added dynamic updates for all components

**Comment by divyanshu013** [comment]
@metagrover we can close this if it looks good

**Comment by divyanshu013** [comment]
Moving to https://github.com/appbaseio/reactivebase-native/issues/20
